### ISSUE TITLE
[Server Fatal] System.NullReferenceException

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#21]
```
[Server Fatal] System.NullReferenceException: Object reference not set to an instance of an object.

   at Vintagestory.GameContent.EntityBehaviorEmotionStates.OnEntityReceiveDamage(DamageSource damageSource, Single& damage)

   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage_Patch1(Entity this, DamageSource damageSource, Single damage)

   at wildcraft.BerryBush.OnEntityInside(IWorldAccessor world, Entity entity, BlockPos pos)

   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)

   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)

   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt)

   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)

   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnGameTick(Single deltaTime)

   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)

   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)

   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)

   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)

   at Vintagestory.Server.ServerMain.Process()
```

**Comment by gabriella-campos-davis** [comment]
Are you using any modded creatures/ does this happen only sometimes?  Any additional information you could provide would be helpful
