### ISSUE TITLE
[Fatal] System.NullReferenceException

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#22]
[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorEmotionStates.OnEntityReceiveDamage(DamageSource damageSource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage_Patch1(Entity this, DamageSource damageSource, Single damage)
   at wildcraft.PoisonOak.OnTick()
   at BuffStuff.BuffManager.<>c.<Initialize>b__12_6(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()

**Comment by gabriella-campos-davis** [comment]
I'll be looking into this, and I'll probably be adding more protections to prevent this in the next release. thanks for the log, I haven't come across this.

**Comment by gabriella-campos-davis** [comment]
Hey, see if you get this again with Wildcraft 1.3.0
