### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#29]
[Server Fatal] System.ArgumentNullException: BESeedling herb block is Null. Exiting.

Parameter name: herbBlock

   at wildcraft.BESeedling.CheckGrow(Single dt)

   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 106

   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 123

   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 768

**Comment by WickedSchnitzel** [comment]
now crashing the server constantly, even after restarting

**Comment by gabriella-campos-davis** [comment]
When was this world created? Is it new or an update from 1.16?

**Comment by gabriella-campos-davis** [comment]
I pushed an attempted fix for this in 1.4.2, let me know if it continues

**Comment by WickedSchnitzel** [comment]
1.4.1 and a fresh 1.17 world. Will try the new version after work.Am 09.09.2022 23:18 schrieb Gabriella Campos-Davis ***@***.***>:
I pushed an attempted fix for this in 1.4.2, let me know if it continues

**Comment by gabriella-campos-davis** [comment]
I found some additional culprits of crashes in BESeedling, and fixed them for version 1.4.4, so I'm gonna close this unless I get additional crash reports
