### ISSUE TITLE
Crash to desktop upon clicking a beam in the handbook

### ISSUE THREAD

**Issue by evadw** [slightlycolorblind/Wildcraft#38]
Here's the crash log. Let me know if you need any other logs.

Running on 64 bit Windows with 24 GB RAM 
Game Version: v1.18.0-rc.3 (Unstable)
4/11/2023 8:27:29 AM: Critical error occurred in the following mod: wildcraft@1.6.0
Loaded Mods: aculinaryartillery@1.0.12, weaponpacka@1.2.4, tonwexp@1.1.0, backpackpackplus@1.0.3, foundrymod@1.0.0, weaponpackg@1.0.1, hideandfabric@1.2.7, meteoricexpansion@1.2.3, plantmat@1.4.0, potontheshelf@1.0.0, primitivesurvival@3.1.5, qptech@, ropebucket@1.0.0, sortablestorage@1.8.0, spidersilk@1.2.2, superfuel@2.0.7, locustmod@2.3.6, game@1.18.0-rc.3, wildcraft@1.6.0, animalcages@2.1.1, betterfirepit@1.0.0, carryon@1.0.0-rc.1, commonlib@2.0.3, expandedfoods@1.6.5, sailboat@1.0.0, khat@1.0.0, lichen@1.6.1, medievalexpansion@3.9.0, ovenfuel@1.0.0, petai@1.6.0, claywheel@1.0.1, prospectorinfo@4.1.4, resinlightsbymad@1.0.1, usefulstuff17@1.1.3, creative@1.18.0-rc.3, vsquest@0.2.0, survival@1.18.0-rc.3, vsvillage@0.7.1, xlib@0.7.0-pre.3, xmelee@0.0.10, xrowboat@0.0.5, metalrecovery@0.1.18-rc.2, bullseye@2.5.0-rc.1, em@2.0.0-pre.5, feverstonehorses@1.4.1, foxtaming@1.0.0-pre.1, glassmaking@1.3.4, stickcrafting@1.0.0, tpnet@1.10.0, wolftaming@1.6.0, xskills@0.7.0-pre.5, bricklayers@2.0.0-pre.4
Involved Harmony IDs: glassmaking
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at wildcraft.BlockMossCoating.GetDrops(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.API.Common.Block.GetHandbookDropsFromBreakDrops(ItemStack handbookStack, IPlayer forPlayer) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1108
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch0(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 118
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 112
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 318
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 118
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 175
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1849
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by gabriella-campos-davis** [comment]
1.6.1 should fix this crash (not really sure why my unused moss test was causing crashes, but I removed it and the crashes went away).
