### ISSUE TITLE
Fruit tree crash

### ISSUE THREAD

**Issue by SmeeSlug** [slightlycolorblind/Wildcraft#48]
Sorry I know there's a lot of mods and I can't be certain it was wildcraft specifically and not a conflict with another mod, but hopefully you can have a little look.
Crashing when the game attempts to load areas, presumably ones with a wildcraft fruit tree asset?

13.5.2023 18:28:19 [Notification] Track Cave Mix () now started
13.5.2023 18:28:44 [Error] Couldn't write to log file, failed formatting For render in fruit tree block wildcrafttrees:fruittree-foliage, defined texture {1}, no such texture found. (FormatException)
13.5.2023 18:28:44 [Fatal] Game Version: v1.18.3 (Stable)
13/05/2023 18:28:44: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.12, ancienttools@1.5.4, autosifter@1.1.0, bandedgeckos@1.0.1, bike@1.1.2, buildersblocks@1.0.0, cairns@1.0.0, chiseltools@1.8.4, compass2@2.0.0, cralutweaks@1.0.2, extraclayforming@1.0.0, fancydoors@1.1.1, fulldrop@1.0.0, healingwhilesleepingfix@1.0.1, hideandfabric@1.3.0, indappledgroves@0.4.9-rc.8, knobtailedgeckos@1.0.0, leopardgeckos@1.0.1, lumbersling@1.0.0, moretreesmoreseeds@1.0.0, unochre@1.1.0, pondfrogsi@1.0.4, pondfrogsii@1.0.0, pondfrogsiii@1.0.0, primitivesurvival@3.1.9, rainfrogs@1.0.2, specializedbags-10Slot@0.4.2, spyglass@0.4.5, ssppvv@1.0.4, game@1.18.3, wildcrafttrees@1.1.5, wildcraft@1.6.5, alchemy@1.6.11, alloycalculator@1.0.0, animalcages@2.1.5, betterfirepit@1.1.0, branchcutter@1.0.1, butterfly@1.0.0, canbeignited@1.1.0, cancelbooksignature@1.0.0-1.18.0-pre.1, carryon@1.0.0, commonlib@2.0.4, cosmosis@0.5.1, expandedfoods@1.6.5, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, fromgoldencombs@1.4.16-rc.2, glidervar@1.1.0, immersivecrafting@1.1.1, sailboat@1.1.0, lavoisier@1.2.7, morepiles@1.3.0, mcrate@1.0.4, notenoughfirewood@1.0.0, petai@1.7.3, recyclebags@1.0.1, recycleclothes@1.0.0, tablet@0.1.4, usefulstuff17@1.1.4, vanvar@3.1.1, creative@1.18.3, vsquest@0.4.1, survival@1.18.3, vsvillage@0.7.2, wildfarmingrevival@1.0.5, woodbarrels@1.0.4, woodchests@1.0.5, xlib@0.7.1, chemistrylib@1.1.1, em@2.1.1, feverstonewilds@1.2.0, foxtaming@1.2.0, simplewinddirection@1.0.2, xinvtweaks@1.5.2, xskills@0.7.1, bricklayers@2.0.0, kosfire@1.1.2, kosphotography@1.2.0, coloredjugs@1.0.0
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 161
   at Vintagestory.API.Common.LogEntryDelegate.Invoke(EnumLogType logType, String message, Object[] args)
   at Vintagestory.GameContent.BlockEntityFruitTreePart.getOrCreateTexPos(AssetLocation texturePath) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 171
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 190
   at Vintagestory.GameContent.BlockEntityFruitTreeFoliage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeFoliage.cs:line 62
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 420
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 411
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by SmeeSlug** [comment]
Veerry sorry realising it's wildcraft TREES and that is not your mod
