### ISSUE TITLE
[Fatal] System.NullReferenceException

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#6]
[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorEmotionStates.OnEntityReceiveDamage(DamageSource damageSource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage)
   at wildcraft.BerryBush.OnEntityInside(IWorldAccessor world, Entity entity, BlockPos pos)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()

**Comment by gabriella-campos-davis** [comment]
Any more info on how this crash happened? playing with any other mods? Seems this happened when something was to supposed to get damaged when going through a berry bush.

**Comment by WickedSchnitzel** [comment]
I just saw this in the console. No clue otherwise. We got custom animals and mobs, our own and from mods like lichen, primitive survival or thecritterspack

On März 3 2022, at 11:17 pm, Gabb ***@***.***> wrote:
>
>
> Any more info on how this crash happened? playing with any other mods? Seems this happened when something was to supposed to get damaged when going through a berry bush.
> —
> Reply to this email directly, view it on GitHub ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2Fslightlycolorblind%2FWildcraft%2Fissues%2F6%23issuecomment-1058555535&recipient=cmVwbHkrQU9YV0VHRjdWQ0pTTk40VFVSSElGWUdBRlpZUTdFVkJOSEhFS0VUUFhZQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXWEGE7WQ4D23MUAE6QRUDU6E3A7ANCNFSM5P3OUTJA&recipient=cmVwbHkrQU9YV0VHRjdWQ0pTTk40VFVSSElGWUdBRlpZUTdFVkJOSEhFS0VUUFhZQHJlcGx5LmdpdGh1Yi5jb20%3D).
> Triage notifications on the go with GitHub Mobile for iOS ***@***.***/2?redirect=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&recipient=cmVwbHkrQU9YV0VHRjdWQ0pTTk40VFVSSElGWUdBRlpZUTdFVkJOSEhFS0VUUFhZQHJlcGx5LmdpdGh1Yi5jb20%3D) or Android ***@***.***/3?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&recipient=cmVwbHkrQU9YV0VHRjdWQ0pTTk40VFVSSElGWUdBRlpZUTdFVkJOSEhFS0VUUFhZQHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you authored the thread.
>



--
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by gabriella-campos-davis** [comment]
Hey,  sorry for following up late, I just want to clarify that this was indeed a crash you experienced? Regardless, I'll see if I an fix this for the next version..

**Comment by gabriella-campos-davis** [comment]
should hopefully be fixed in 1.2.1
